=== spartan182/XML-Actividad-Evaluable/Nicolas_Andrade.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:simpleType name="tipoDni">
   <xs:restriction  base="xs:string">
      <xs:pattern value="[0-9]{8}[A-Z]|[a-z]"/>
   </xs:restriction>
</xs:simpleType>

<xs:simpleType name="mentiroso">
   <xs:restriction  base="xs:string">
       <xs:pattern value="Real|Inventada|real|inventada|REAL|INVENTADA"/>
   </xs:restriction>
</xs:simpleType>

<xs:simpleType name="SiNo">
   <xs:restriction  base="xs:string">
       <xs:pattern value="Si|No|si|no|SI|NO"/>
   </xs:restriction>
</xs:simpleType>

<xs:simpleType name="Imagenes">
   <xs:restriction  base="xs:string">
       <xs:pattern value="[a-zA-Z0-9] *.jpg"/>
   </xs:restriction>
</xs:simpleType>


<xs:element name="curriculum">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="DatosPersonales">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="nombre" type="xs:string"/>
                                                 <xs:element name="apellidos" type="xs:string"/>
                                                 <xs:element name="FechaNat" type="xs:string"/>
                                                 <xs:element name="LugarNat" type="xs:string"/>
                                                 <xs:element name="nacionalidad" type="xs:string"/>
                                                 <xs:element name="dni" type="tipoDni"/>
                                                 <xs:element name="foto" type="xs:string"/>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="DatosContacto">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="TipoVia" type="xs:string"/>
                                                 <xs:element name="nombre" type="xs:string"/>
                                                 <xs:element name="numero" type="xs:int"/>
                                                 <xs:element name="portal" type="xs:string"/>
                                                 <xs:element name="escalera" type="xs:string"/>
                                                 <xs:element name="piso" type="xs:int"/>
                                                 <xs:element name="puerta" type="xs:int"/>
                                                 <xs:element name="cp" type="xs:int"/>
                                                 <xs:element name="pais" type="xs:string"/>
                                                 <xs:element name="email" type="xs:string"/>
                                                 <xs:element name="TelMovil" type="xs:int"/>
                                                 <xs:element name="TelFijo" type="xs:int"/>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="DatosContactoAdicionales">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="web" type="xs:string"/>
                                                 <xs:element name="linkedin" type="xs:string"/>
                                                 <xs:element name="facebook" type="xs:string"/>
                                                 <xs:element name="twitter" type="xs:string"/>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="Formacion">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="estudio" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="nombre" type="xs:string"/>
                                                                      <xs:element name="lugar" type="xs:string"/>
                                                                      <xs:element name="FechaInicio" type="xs:string"/>
                                                                      <xs:element name="FechaFin" type="xs:string"/>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="Idiomas">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="idioma" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="nombre" type="xs:string"/>
                                                                      <xs:element name="NivelOral" type="xs:string"/>
                                                                      <xs:element name="NivelComprension" type="xs:string"/>
                                                                      <xs:element name="NivelEscritura" type="xs:string"/>
                                                                      <xs:element name="materno" type="xs:string"/>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="EsperienciaLaboral">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="experiencia" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="empresa" type="xs:string"/>
                                                                      <xs:element name="puesto" type="xs:string"/>
                                                                      <xs:element name="FechaInicio" type="xs:string"/>
                                                                      <xs:element name="FechaFin" type="xs:string"/>
                                                                      <xs:element name="RealoInventada" type="mentiroso"/>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="Competencias">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="liderzgo" type="xs:int"/>
                                                 <xs:element name="TrabajoEnEquipo" type="xs:int"/>
                                                 <xs:element name="iniciativa" type="xs:int"/>
                                                 <xs:element name="creatividad" type="xs:int"/>
                                                 <xs:element name="autonomia" type="xs:int"/>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="DatosAdicionales">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="aficiones" type="xs:string"/>
                                                 <xs:element name="DisponibilidadViaje" type="xs:string"/>
                                                 <xs:element name="VehiculoPropio" type="xs:string"/>
                                                 <xs:element name="TipoCarnet" type="xs:string"/>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== spartan182/XML-Actividad-Evaluable/Nicolas_Andrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculum 
  xsi:noNamespaceSchemaLocation="Nicolas_Andrade.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <DatosPersonales>
          <nombre>Nicolas</nombre>
          <apellidos>Andrade  Murcia</apellidos>
          <FechaNat>17/05/1997</FechaNat>
          <LugarNat>Espanya</LugarNat>
          <nacionalidad>Espanyola</nacionalidad>
          <dni>26662089G</dni>
          <foto>mifoto.jpg</foto>
    </DatosPersonales>
    
        <DatosContacto>
          <TipoVia>Calle</TipoVia>
          <nombre>Paco Ibañez</nombre>
          <numero>45</numero>
          <portal>59</portal>
          <escalera>1</escalera>
          <piso>3</piso>
          <puerta>8</puerta>
          <cp>46470</cp>
          <pais>España</pais>
          <email>andrade16841@outlook.es</email>
          <TelMovil>610672000</TelMovil>
          <TelFijo>96544528</TelFijo>
    </DatosContacto>
    
    <DatosContactoAdicionales>
         <web>www.asdNicolas.es</web>
          <linkedin>Nicolas AM</linkedin>
          <facebook>Nicolas Am</facebook>
          <twitter>nicolas182</twitter>
    </DatosContactoAdicionales>
    
    <Formacion>
        <estudio>
          <nombre>Graduado escolar</nombre>
          <lugar>Valencia</lugar>
          <FechaInicio>18/05/2004</FechaInicio>
          <FechaFin>24/06/2008</FechaFin>
        </estudio> 
        <estudio>
          <nombre> Grado medio TSMT</nombre>
          <lugar>Valencia</lugar>
          <FechaInicio>18/05/2008</FechaInicio>
          <FechaFin>24/06/20012</FechaFin>
        </estudio> 
        <estudio>
          <nombre>Grado superior DAW</nombre>
          <lugar>Valencia</lugar>
          <FechaInicio>15/05/2012</FechaInicio>
          <FechaFin>1/06/2014</FechaFin>
        </estudio> 
    </Formacion>
    
    <Idiomas>
          <idioma>
            <nombre>Espanyol</nombre>
            <NivelOral>Alto</NivelOral>
            <NivelComprension>Alto</NivelComprension>
           <NivelEscritura>Alto</NivelEscritura>
            <materno>Si</materno>
          </idioma>
          <idioma>
            <nombre>ingles</nombre>
            <NivelOral>Alto</NivelOral>
            <NivelComprension>Alto</NivelComprension>
           <NivelEscritura>Medio</NivelEscritura>
            <materno>No</materno>
          </idioma>
          <idioma>
            <nombre>Aleman</nombre>
            <NivelOral>Medio</NivelOral>
            <NivelComprension>Medio</NivelComprension>
           <NivelEscritura>Medio</NivelEscritura>
            <materno>No</materno>
          </idioma>
    </Idiomas>
    
    <EsperienciaLaboral>
        <experiencia>
          <empresa>Cofrentes	</empresa>
          <puesto>Tecnico</puesto>
          <FechaInicio>15/08/2014</FechaInicio>
          <FechaFin>1/08/2015</FechaFin>
          <RealoInventada>Real</RealoInventada>
        </experiencia>
        <experiencia>
          <empresa>Cofrentes	</empresa>
          <puesto>Jefe supervisor</puesto>
          <FechaInicio>15/08/2015</FechaInicio>
          <FechaFin>05/11/2018</FechaFin>
          <RealoInventada>Real</RealoInventada>
        </experiencia>
    </EsperienciaLaboral>
    
    <Competencias>
        <liderzgo>5</liderzgo>
        <TrabajoEnEquipo>4</TrabajoEnEquipo>
        <iniciativa>5</iniciativa>
        <creatividad>4</creatividad>
        <autonomia>5</autonomia>
    </Competencias>
    
    <DatosAdicionales>
        <aficiones>Videojuegos</aficiones>
        <DisponibilidadViaje>Si</DisponibilidadViaje>
        <VehiculoPropio>Si</VehiculoPropio>
        <TipoCarnet>B</TipoCarnet>
    </DatosAdicionales>
    
</curriculum>
